# Generated by Django 3.1.2 on 2020-11-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_local', models.CharField(max_length=200)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('preserved_area', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('description', models.TextField(null=True)),
                ('description_local', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_local', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('preserved_area', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('isa_id', models.IntegerField(null=True)),
                ('biome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.biome')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
        migrations.AddField(
            model_name='biome',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
