# Generated by Django 5.2.8 on 2025-11-11 01:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "verbose_name_plural": "Communities",
            },
        ),
        migrations.RemoveField(
            model_name="biome",
            name="preserved_area",
        ),
        migrations.RemoveField(
            model_name="biome",
            name="total_area",
        ),
        migrations.RemoveField(
            model_name="country",
            name="language",
        ),
        migrations.RemoveField(
            model_name="country",
            name="name_local",
        ),
        migrations.RemoveField(
            model_name="land",
            name="isa_id",
        ),
        migrations.RemoveField(
            model_name="land",
            name="preserved_area",
        ),
        migrations.RemoveField(
            model_name="land",
            name="state",
        ),
        migrations.RemoveField(
            model_name="land",
            name="total_area",
        ),
        migrations.AddField(
            model_name="land",
            name="source_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="land",
            name="source_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="source_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="source_raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="name_local",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="biome",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biome",
            name="description_local",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biome",
            name="name_local",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="biome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lands",
                to="app.biome",
            ),
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_local", models.CharField(blank=True, max_length=200, null=True)),
                ("code", models.CharField(max_length=10)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipalities",
                        to="app.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.AddField(
            model_name="land",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lands",
                to="app.municipality",
            ),
        ),
    ]
