# Generated by Django 3.1.2 on 2020-11-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='land',
            name='biome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='app.biome'),
        ),
    ]
