# Generated by Django 5.2.8 on 2025-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_community_remove_biome_preserved_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="communities",
            field=models.ManyToManyField(
                blank=True, related_name="lands", to="app.community"
            ),
        ),
    ]
