# Generated by Django 5.2.8 on 2025-11-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_land_communities"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="land",
            unique_together={("source_name", "source_id")},
        ),
    ]
