# Generated by Django 5.2.8 on 2025-11-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_land_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.country",
            ),
        ),
    ]
